name: project5
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  flutter_inappwebview: ^5.8.0
  in_app_review:
  hive_flutter: ^1.1.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf